### ISSUE TITLE
Silent Storage Service crash

### ISSUE THREAD

**Issue by michelmegens** [sensate-iot/platform-network#5]
## *Who* is the bug affecting?
Clients using the storage service.

## *What* is affected by this bug?
Applications using the storage service.

## *When* does this occur?
After restarting the internal MQTT broker.

## Expected behavior (i.e. solution)
- Restart of the storage service, or;
- Rebuild of the internal MQTT connection.

## Other Comments
Logs of the storage service:

```
storage-service_1    | Unhandled exception. MQTTnet.Exceptions.MqttCommunicationTimedOutException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.
storage-service_1    |    at MQTTnet.PacketDispatcher.MqttPacketAwaiter`1.WaitOneAsync(TimeSpan timeout)
storage-service_1    |    at MQTTnet.Client.MqttClient.SendAndReceiveAsync[TResponsePacket](MqttBasePacket requestPacket, CancellationToken cancellationToken)
storage-service_1    |    at MQTTnet.Client.MqttClient.SubscribeAsync(MqttClientSubscribeOptions options, CancellationToken cancellationToken)
storage-service_1    |    at SensateIoT.Platform.Network.Common.MQTT.AbstractMqttClient.SubscribeAsync(String topic) in /build/SensateIoT.Platform.Network.Common/MQTT/AbstractMqttClient.cs:line 124
storage-service_1    |    at SensateIoT.Platform.Network.Common.MQTT.AbstractMqttClient.OnConnectAsync() in /build/SensateIoT.Platform.Network.Common/MQTT/AbstractMqttClient.cs:line 131
storage-service_1    |    at SensateIoT.Platform.Network.Common.MQTT.InternalMqttClient.OnConnectAsync() in /build/SensateIoT.Platform.Network.Common/MQTT/InternalMqttClient.cs:line 65
storage-service_1    |    at SensateIoT.Platform.Network.Common.MQTT.AbstractMqttClient.OnConnect_Handler() in /build/SensateIoT.Platform.Network.Common/MQTT/AbstractMqttClient.cs:line 166
storage-service_1    |    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
storage-service_1    |    at System.Threading.ThreadPoolWorkQueue.Dispatch()
storage-service_1    | info: SensateIoT.Platform.Network.StorageService.Application.ApplicationHost[0]
storage-service_1    |       Starting SensateIoT.Platform.Network.StorageService 1.4.6.0
storage-service_1    | info: SensateIoT.Platform.Network.Common.Services.Metrics.MetricsService[0]
storage-service_1    |       Starting metrics server on http://+:8080/metrics/
storage-service_1    | crit: SensateIoT.Platform.Network.Common.MQTT.InternalMqttClient[0]
storage-service_1    |       Unable to complete background service execution!
storage-service_1    |       MQTTnet.Exceptions.MqttCommunicationException: Error while connecting with host 'broker002-001.prod.sensateiot.com:1883'.
storage-service_1    |        ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
storage-service_1    |          at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
storage-service_1    |          at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
storage-service_1    |          at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
storage-service_1    |       --- End of stack trace from previous location ---
storage-service_1    |          at MQTTnet.Implementations.CrossPlatformSocket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
storage-service_1    |          --- End of inner exception stack trace ---
storage-service_1    |          at MQTTnet.Implementations.CrossPlatformSocket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
storage-service_1    |          at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
storage-service_1    |          at MQTTnet.Internal.MqttTaskTimeout.WaitAsync(Func`2 action, TimeSpan timeout, CancellationToken cancellationToken)
storage-service_1    |          at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
storage-service_1    |          at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
storage-service_1    |          at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
storage-service_1    |          at SensateIoT.Platform.Network.Common.MQTT.AbstractMqttClient.Connect(String user, String passwd) in /build/SensateIoT.Platform.Network.Common/MQTT/AbstractMqttClient.cs:line 112
storage-service_1    |          at SensateIoT.Platform.Network.Common.MQTT.InternalMqttClient.ExecuteAsync(CancellationToken token) in /build/SensateIoT.Platform.Network.Common/MQTT/InternalMqttClient.cs:line 34
storage-service_1    |          at SensateIoT.Platform.Network.Common.Services.Background.BackgroundService.InternalExecuteAsync(CancellationToken ct) in /build/SensateIoT.Platform.Network.Common/Services/Background/BackgroundService.cs:line 57
storage-service_1    | info: SensateIoT.Platform.Network.Common.MQTT.InternalMqttClient[0]
storage-service_1    |       Internal MQTT client disconnected!
```

**Comment by michelmegens** [comment]
Closed in #6.
